### ISSUE TITLE
http://vzaar.com/settings/ link in readme is 404

### ISSUE THREAD

**Issue by looshi** [vzaar/vzaar-api-php#4]
no big deal, but this link in the readme http://vzaar.com/settings/ brings user to 404 page : 

"In order to use vzaar API, you need to have a valid user name and API token that you can get from your vzaar dashboard at http://vzaar.com/settings/ : " 

I think it should be http://app.vzaar.com/settings/api .

**Comment by cfx** [comment]
Fixed. Thanks looshi!

**Comment by looshi** [comment]
@cfx 
no worries, this is a really great library!  thanks.  The examples rule, I'm already up and running.  Do you guys have any plans to add a Node.js version of this library?

**Comment by alol** [comment]
Hey @looshi, it just so happens that @cfx recently finished working on an initial release of an npm package for the vzaar API, so you can use it in node.js :grinning:. You can find the repo here: https://github.com/vzaar/vzaar-api-nodejs, and it's on npm here: https://www.npmjs.com/package/vzaar

As this is a brand new library, we're keen to hear any feedback you may have, so please let us know how you get on with it!
